name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: docker-compose -f docker-compose-build.yml build
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push frontend image
      run: docker push paulbricman/conceptarium_frontend:latest
    - name: Push backend image
      run: docker push paulbricman/conceptarium_backend:latest
    
