name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
        
      - name: Run tests
        run: pytest
          
      
